### ISSUE TITLE
Why compile from scratch instead of using Debian package?

### ISSUE THREAD

**Issue by mr-c** [CancerCollaboratory/dockstore-tool-samtools-sort#1]
The following versions are available: https://packages.debian.org/search?keywords=samtools

Archived versions are at http://snapshot.debian.org/package/samtools/

It would make the Dockerfile much simpler and better centralized the maintenance of samtools. If you have any problem with our packaging please let me know or make a contribution to Debian directly.

**Comment by denis-yuen** [comment]
@mr-c  We're already using the apt package. If you're coming from production Dockstore, we just haven't refreshed the cached contents yet.

**Comment by mr-c** [comment]
Great to hear :-) Yeah, I saw https://dockstore.org/containers/quay.io/cancercollaboratory/dockstore-tool-samtools-sort and didn't check the contents of this repo.
